---
services:
  mysql:
    container_name: mysql-db
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pa$$word1
      MYSQL_ROOT_HOST: "%"
    restart: unless-stopped
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: