---
services:
  mysql:
    container_name: mysql-db
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pa$$word1
      MYSQL_DATABASE: coffee_menu
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppasswd
    restart: unless-stopped
    volumes:
        - ./docker/init-sql.sql:/docker-entrypoint-initdb.d/init-sql.sql
        - my-db:/var/lib/mysql
volumes:
  my-db:
